# Generated by Django 5.1.2 on 2024-12-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('developers', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('cover', models.ImageField(upload_to=None)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
