# Generated by Django 5.1.2 on 2024-12-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_rename_games_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(upload_to='static/Catalog/game_icons/'),
        ),
    ]
