# Generated by Django 5.1.2 on 2024-12-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_alter_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
