# Generated by Django 5.1.2 on 2025-02-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0004_alter_game_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=368),
        ),
    ]
